title: DJ Jolene
email: hello@djjlone.com
tagline: Booty-shaking house music. Underground. NYC.
description: > # this means to ignore newlines until "baseurl:"
  DJ Jolene has been rocking NYC with her blend of deep sexy house music for over a decade. She is the founder of the House channel for the popular Digitally Imported internet radio station and has also taught regularly at New York's Scratch DJ Academy. Her driving, bass-heavy mixes are influenced by the cities in which she has resided: London, San Francisco and New York.
baseurl: "" # the subpath of your site, e.g. /blog
url: "djjolene.com"
twitter_username: djjolene
github_username: djjolene

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
